# Generated by Django 4.1.5 on 2023-01-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicteam',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
