# Generated by Django 4.1.5 on 2023-01-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_basicteam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicteam',
            name='nickname',
            field=models.CharField(default='team', max_length=30),
            preserve_default=False,
        ),
    ]
