# Generated by Django 4.1.7 on 2023-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicplayer',
            old_name='id_active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='basicplayer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
